language: node_js
node_js:
  - 12

services:
  - postgresql

before_script:
  - psql -c 'create database taxi_trips;' -U postgres
  - psql -a -d taxi_trips -f sql/tables.sql -U postgres
  - psql -a -d taxi_trips -f sql/data.sql -U postgres